name: Serious Coco
favicon: null
layout_spectrum: 0.09233293426223099
typography_spectrum: 0.23796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.19220879930071533
  lightness: 0.6255816454067826
  saturation: 0.2572792212013155
  rhythmicContrast: 0.90243513090536
purpose: []
